### PR TITLE
Interactive To-Do List Functionality 

### PR DESCRIPTION
**Pull request by zamcham**
- New module that handles task completion
- Implements function to clear all completed tasks
- Double-click on a task to edit it

### CODE REVIEW

**Review by ishimwezachee — COMMENTED** [review]
Hi  @zamcham , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
image

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow. For it is indivitual project your base branch should be `dev `branch 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by zamcham** [comment]
> Hi @zamcham ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code. 
> 
> ## Invalid Code Review Request
> You have submitted a project, that has incorrect gitflow. For it is indivitual project your base branch should be `dev `branch
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

There is no `dev` branch in my repository, and according to the [GitHub flow documentation](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md), the new branch has to be based on the `main` branch of my repo, which is what I did.

**Comment by arslanbisharat** [comment]
Hi @zamcham, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct Gitflow. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by AmaduKamara — COMMENTED** [review]
# Status: Invalid Submission ❌ ❌ ❌

Hi @zamcham,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow proper git-flow.

- [ ] It would be nice if you could create a dev branch, then configure it to be the default branch, and then make subsequent branches that point to the dev branch. that way after the whole project and all feature branches are merged into the dev branch, you can then make a PR from dev to main. Kindly follow a proper gitflow for your branches 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

**Pull request closed without merging**
